# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerImageRepository: 'prashhome/weatherapi'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'MyAgentPool'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Prashhome Docker Hub'
        repository: $(dockerImageRepository)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
- stage: Provision
  displayName: Terraform provision stage
  dependsOn: Build
  jobs:
  - job: Provison
    displayName: Provision container instance job
    pool:
      name: 'MyAgentPool'
    variables:
    - group: TerraformEnvVars
    steps:
    - script: |
        set -e

        terraform init -input=false
        terraform apply -input=false -auto-approve
      name: RunTerraform
      displayName:  Run Terraform
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        TF_VAR_DockerImageBuild: $(dockerImageRepository):$(tag)
